### ISSUE TITLE
TagsInput should prevent enter key

### ISSUE THREAD

**Issue by terion-name** [creativetimofficial/ct-vue-argon-dashboard-pro#10]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Adding tag in `TagsInput` via `enter` key does not trigger form submission

# Current Behavior

It does

# Failure Information (for bugs)

n/a

## Steps to Reproduce

1. Create a form with `onSubmit` handler and a tags input inside
2. Add a tag by hitting enter

## Context

n/a

## Failure Logs

n/a

===

## Solution

```
// components/Inputs/TagsInput.vue
<input
      ...
     @keydown.enter.prevent=""
    />
```

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
