### ISSUE TITLE
SrollBar side menu

### ISSUE THREAD

**Issue by carlosalbertocruz** [creativetimofficial/ct-vue-argon-dashboard-pro#11]
Perfect scrollbar in sidebar not working in argon dash pro.

**Comment by javinievas** [comment]
There is a mistake in the file DashboardLayout.vue

Just change the line:
this.initScrollbar();
with:
this.initScrollbar('sidenav');

and scrollbar starts to work.
That function requires the classname of the items that you want to apply on.

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
