### ISSUE TITLE
Donut and Pie chart mouse over shows labels pop-over other slices on other side of horizontal axis

### ISSUE THREAD

**Issue by rparundekar** [creativetimofficial/ct-vue-argon-dashboard-pro#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version (vue-argon-dashboard-pro-v1.1.1.html.zip)
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
In the donut chart and the pie chart, the mouse over event should show the value for that slice. While the mouse is moved in the same slice, the label should stay the same. 

# Current Behavior
While the mouse is moved in the same slice, the label changes according to the horizontal location of the mouse, but the label pop over changes to other slices. To get the label for the slice, you have to be in the angular center of that slice. If you are at the ends of the slice, the label moves to some other slice. 

# Failure Information (for bugs)
Seems to be a bug, since vuechart.js version does not have this issue. http://demo.vue-chartjs.org/

## Steps to Reproduce
1. Unzip the vue argon dashboard pro from - vue-argon-dashboard-pro-v1.1.1.html.zip 
2. In the directory, `npm i`
3. Go to http://localhost:8080/#/charts and move mouse on the donut chart or the pie chart.

## Context
* Device: Macbook Air
* Operating System: 10.14.6 
* Browser and Version: Google Chrome Version 76.0.3809.132

## Failure Logs
No errors in the console. 

Hunch: Seems to be an angular conversion issue that chooses the slice on the flip side of the horizontal axis.

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
