### ISSUE TITLE
BaseInput does not respect `group` prop.

### ISSUE THREAD

**Issue by jamiewildehk** [creativetimofficial/ct-vue-argon-dashboard-pro#14]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

`group` prop should suppress group classes

# Current Behavior

`group` prop exists in documentation only

What is the current behavior?

`group` prop ignored

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Create `<base-input :group="false">` element.
Please include any relevant log snippets or files here.

(I wanted to suppress `form-group` via this prop - docs are ambiguous on if input group is actually what's intended to be suppressed - my goal was to have "forgot password?" directly under the control - and the implicit form group was preventing that. I have explicitly wrapped the input and forgot password link in a form-group myself to ensure correct tabbing behaviour)

```
diff --git a/src/components/argon/Inputs/BaseInput.vue b/src/components/argon/Inputs/BaseInput.vue
index 1e31405..752a9e6 100644
--- a/src/components/argon/Inputs/BaseInput.vue
+++ b/src/components/argon/Inputs/BaseInput.vue
@@ -1,6 +1,6 @@
 <template>
-    <div class="form-group"
-         :class="[
+    <div :class="[
+       {'form-group': group},
        {'input-group': hasIcon},
        {'has-danger': error},
        {'focused': focused},
@@ -92,7 +92,12 @@ export default {
     },
     addonLeftIcon: {
       type: String,
-      description: "Addont left icon"
+      description: "Addon left icon"
+    },
+    group: {
+      type: Boolean,
+      description: "Should this be a form-group",
+      default: true
     }
   },
   data() {
```

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
