### ISSUE TITLE
Bug report + fix: mousedown inside a modal then mouseup outside of it closes the modal

### ISSUE THREAD

**Issue by Dinduks** [creativetimofficial/ct-vue-argon-dashboard-pro#15]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Only clicking outside a modal should close it

# Current Behavior

Clicking inside the modal and releasing the click outside the modal makes it close.

This often happens when text is selected.

## Fix

```diff
diff --git a/src/components/Modal.vue b/src/components/Modal.vue
index fcd82bc..1a79fdc 100644
--- a/src/components/Modal.vue
+++ b/src/components/Modal.vue
@@ -1,7 +1,8 @@
 <template>
   <SlideYUpTransition :duration="animationDuration">
     <div class="modal fade"
-         @click.self="closeModal"
+         @mousedown.self="closeMouseDown"
+         @mouseup.self="closeMouseUp"
          :class="[{'show d-block': show}, {'d-none': !show}, {'modal-mini': type === 'mini'}]"
          v-show="show"
          tabindex="-1"
@@ -47,6 +48,11 @@
     components: {
       SlideYUpTransition
     },
+    data() {
+      return {
+        wasModalBorderClicked: false,
+      };
+    },
     props: {
       show: Boolean,
       showClose: {
@@ -104,7 +110,16 @@
       closeModal() {
         this.$emit("update:show", false);
         this.$emit("close");
-      }
+      },
+      closeMouseDown() {
+        this.wasModalBorderClicked = true;
+      },
+      closeMouseUp() {
+        if (this.wasModalBorderClicked) {
+          this.closeModal();
+        }
+        this.wasModalBorderClicked = false;
+      },
     },
     watch: {
       show(val) {
```

**Comment by cristijora** [comment]
Thanks for the detailed explanation @Dinduks 
I believe the final solution can be a bit more simple with only `@mousedown.self="closeModal"` on the modal mask. Nice catch!
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
