### ISSUE TITLE
[Bug] Wrong link for starterRouter.js in documentation

### ISSUE THREAD

**Issue by RobertWade** [creativetimofficial/ct-vue-argon-dashboard-pro#16]
### Version
-
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/quick-start.html#quick-start
### Operating System
All
### Device
All
### Browser & Version
All
### Steps to reproduce
https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/quick-start.html#quick-start
### What is expected?
import router from './starterRouter';

Should show Start dashboard according to docs.
### What is actually happening?
Error because starteRouter is not found

---
### Solution
What it should say in the docs:

import router from './routes/starterRouter';
or
import router from '@/routes/starterRouter';

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
