### ISSUE TITLE
Element UI Select CSS Missing

### ISSUE THREAD

**Issue by dejan7** [creativetimofficial/ct-vue-argon-dashboard-pro#17]
Element UI  selects appear unstyled for me 

![image](https://user-images.githubusercontent.com/6208610/68854675-d7b8b680-06dc-11ea-9cea-19ae3e088b8d.png)

                    <base-input label="Simple select">
                        <el-select v-model="selects.simple" filterable
                                   placeholder="Simple select">
                            <el-option v-for="option in selects.languages"
                                       :key="option.label"
                                       :label="option.label"
                                       :value="option.value">
                            </el-option>
                        </el-select>
                    </base-input>

While browsing your demo site, i saw that the component is getting the style from some forms-tables.css file: https://demos.creative-tim.com/vue-argon-dashboard-pro/css/forms~tables.847108d3.css

However, i don't see any similiar file in the pack i downloaded. 

What should i do? 

Thanks

**Comment by yevheniidehtiar** [comment]
i guess you missed this: 
```
"plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
```
in `babel.config.js`

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
