### ISSUE TITLE
Error when running the npm run dev after npm install

### ISSUE THREAD

**Issue by bizjaya** [creativetimofficial/ct-vue-argon-dashboard-pro#18]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [/] I am running the latest version
- [/] I checked the documentation and found no answer
- [/] I checked to make sure that this issue has not already been filed
- [/] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Running the demo after running "npm run dev"

# Current Behavior
Cant run the demo as I'm getting errors : 
![image](https://user-images.githubusercontent.com/10965434/69712100-3a7a6b00-113d-11ea-8fb5-92b1051448f1.png)

# Failure Information (for bugs)

 ERROR  Failed to compile with 1 errors                                                        5:36:09 PM
 error  in ./src/assets/sass/argon.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in C:\Users\devon\OneDrive\Desktop\ezmartside\node_modules\bootstrap\scss\_forms.scss (line 40, column 12)

 @ ./src/assets/sass/argon.scss 4:14-231 14:3-18:5 15:22-239
 @ ./src/plugins/dashboard-plugin.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.121:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by bizjaya** [comment]
I I found out that this was caused because it had downloaded bootstrap 4.4 and not the 4.3.1 as stated in the packages.json file

**Comment by jumadilakbar** [comment]
what solution for this problem?

**Comment by obalado** [comment]
i have the same issue

**Comment by bizjaya** [comment]
I just ran 
npm install bootstrap@4.3.1 --save

The template is not compatible with bootstrap 4.4

**Comment by obalado** [comment]
btw i edit the packaje json and replace the caret with tilde
 "bootstrap": "~4.3.1",

**Comment by obalado** [comment]
just edited the packaje json  "bootstrap": "~4.3.1",

**Comment by jumadilakbar** [comment]
> I just ran
> npm install bootstrap@4.3.1 --save
> 
> The template is not compatible with bootstrap 4.4

this working for me, thanks bro

**Comment by jumadilakbar** [comment]
Ok thanks

**Comment by cristijora** [comment]
Sorry for all the inconveniences caused by this issue everyone!
Indeed having version 4.3.1 should solve the issue. 
We made a small update with many other fixes and locked the bootstrap version so this doesn't happen again in future. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)

**Comment by carbomax** [comment]
I have the same error but I'm using "bootstrap": "4.3.1" dependency
 "dependencies": {
    "@angular/animations": "10.0.10",
    "@angular/common": "10.0.10",
    "@angular/compiler": "10.0.10",
    "@angular/core": "10.0.10",
    "@angular/forms": "10.0.10",
    "@angular/http": "7.2.16",
    "@angular/localize": "^10.0.10",
    "@angular/platform-browser": "10.0.10",
    "@angular/platform-browser-dynamic": "10.0.10",
    "@angular/router": "10.0.10",
    "@ng-bootstrap/ng-bootstrap": "7.0.0",
    "bootstrap": "4.3.1",
    "chart.js": "2.9.3",
    "clipboard": "2.0.6",
    "core-js": "3.6.5",
    "ngx-clipboard": "13.0.1",
    "ngx-toastr": "13.0.0",
    "nouislider": "14.6.1",
    "rxjs": "6.6.2",
    "zone.js": "0.10.3"
  },

ERROR in ./src/assets/scss/argon.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js??ref--14-4!./src/assets/scss/argon.scss)
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: wrong number of arguments (3 for 2) for `form-validation-state'
        on line 246 of node_modules/bootstrap/scss/_forms.scss, in mixin `form-validation-state`
        from line 246 of node_modules/bootstrap/scss/_forms.scss
        from line 35 of C:\Users\MSI GL63 8RD\Desktop\UDEMY_PROJECTS\AGILECOMERCE\argon-dashboard-angular-master\src\assets\scss\argon.scss
>>   @include form-validation-state($state, map-get($data, color), map-get($dat
   -----------^
