### ISSUE TITLE
el-tooltip isn't styled

### ISSUE THREAD

**Issue by Dinduks** [creativetimofficial/ct-vue-argon-dashboard-pro#19]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

`.el-tooltip` to be styled.

# Current Behavior

No style is defined for `.el-tooltip` classes.

**Comment by cristijora** [comment]
Hey @Dinduks Thanks for opening the issue. Can you attach a screenshot as well please ?
Tooltips should have dark background by default. You can check the [docs here](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/components/tooltips.html)

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
