### ISSUE TITLE
Want to add classes on 'form-group' level.

### ISSUE THREAD

**Issue by i0rph** [creativetimofficial/ct-vue-argon-dashboard-pro#20]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Add classes on `form-group` level

# Current Behavior

Classes add on `span` which is parent of `form-group` `div`

# Failure Information (for bugs)

It was working on v1.1 when I add classes on `base-input`. But after updated to latest version it's not working at all. Instead it adds classes on parent `span`. What I want to do is removing `margin-bottom` from specific `base-input`.

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
