### ISSUE TITLE
tabs vertical is not working for the tab-pane

### ISSUE THREAD

**Issue by BranchofApp** [creativetimofficial/ct-vue-argon-dashboard-pro#21]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

To description to be vertical too; like the tab-pane as shown here : https://bootstrap-vue.js.org/docs/components/tabs/#vertical-tabs

# Current Behavior

The description shows up under the tab

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
