### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by RalphBragg** [creativetimofficial/ct-vue-argon-dashboard-pro#22]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Demo's in documentation work

# Current Behavior

Pagination documentation examples here: https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/components/tables.html Don't work. Exceptionally frustrating as the demo that is hosted here; https://demos.creative-tim.com/vue-argon-dashboard-pro/#/ does work.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Pagination documentation examples here: https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/components/tables.html Don't work. Exceptionally frustrating as the demo that is hosted here; https://demos.creative-tim.com/vue-argon-dashboard-pro/#/ does work.
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: OSX
* Operating System: Mac
* Browser and Version: Chrome

## Failure Logs

None

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
