### ISSUE TITLE
Vee-Validate Migration Across Code Base

### ISSUE THREAD

**Issue by MarcusTheSmith** [creativetimofficial/ct-vue-argon-dashboard-pro#23]
# Expected Behavior
Was expecting to follow the suggestions for migrating over the updates by copying the component and asset files, updating the dependencies & have it working. 

# Current Behavior
It required a lot of scouring the code base to find places where vee-validate references needed placed, which were not personal use but part of the template. It would have been nice to have a breakdown of all files that needed updated (which were not part of the ones mentioned). 

# Failure Information (for bugs)
The error we got after making the suggested changes was the following, but it isn't all that helpful. It was mostly an issue of references throughout the code base that needed manually updated or copied over from the new template (some manually so as to not interfere with our custom code)

Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Tr.t.use (vue.runtime.esm.js:5106)
    at Object.install (dashboard-plugin.js:29)
    at Function.Tr.t.use (vue.runtime.esm.js:5107)
    at Module.56d7 (main.js:25)
    at l (bootstrap:89)
    at Object.0 (app.eb69d6da.js:1)
    at l (bootstrap:89)
    at a (bootstrap:45)
    at bootstrap:267
    at app.eb69d6da.js:1

## Steps to Reproduce

1. Copy over components directory
2. Copy over assets directory
3. Compare and update package.json
4. Replace all "v-validate" with new version
5. Try running application and see errors

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Workstation
* Operating System: Windows 10
* Browser and Version: Latest Chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
