### ISSUE TITLE
Modals don't work correctly (Form Import or buttons)

### ISSUE THREAD

**Issue by chrisjenx** [creativetimofficial/ct-vue-argon-dashboard-pro#26]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

- You should be able to input into form
- Close buttons should appear and work

# Current Behavior

- Form input is ignored
- Cancel buttons never appear

# Failure Information (for bugs)

Try your models in the demo!

## Steps to Reproduce

- Go to demo components
- Click Modal
- Click Form
- try and input text into fields.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by wmsoftware-de** [comment]
Reported on 11 Apr 2020, no comment and still open?

**Comment by rarestoma** [comment]
Hi @chrisjenx, @wmsoftware-de 

Thank you for working with our products and sorry for my late response.

To fix the inputs error please go to `src/components/Inputs/BaseInput.vue` and replace `:value="value"` with `v-model="value"`.

According to the modal close buttons, did you try our modals available here: https://demos.creative-tim.com/vue-argon-dashboard-pro/#/components/notifications?

Thank you,
Rares

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
