### ISSUE TITLE
[Bug] Checkbox 'check' image not showing

### ISSUE THREAD

**Issue by simonwaw** [creativetimofficial/ct-vue-argon-dashboard-pro#29]
### Version
1.1.0
### Reproduction link
https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro/issues/28
### Operating System
OSX
### Device
Macbook
### Browser & Version
Chrome 84.0.4147.89
### Steps to reproduce
Refer to https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro/issues/28

### What is expected?
Checkboxes should show 'check' image icon
### What is actually happening?
Seeing a solid filled box (no chckbox)

---
### Solution
Refer to https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro/issues/28

**Comment by dragosct** [comment]
Hi, @simonwaw! Thanks for using our products. The solution is working for you? 

Regards,
Dragos

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
