### ISSUE TITLE
[Bug] Paginated tables search function does not work

### ISSUE THREAD

**Issue by falsetru** [creativetimofficial/ct-vue-argon-dashboard-pro#30]
### Version
1.2.2
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/#/tables/paginated
### Operating System
Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 GNU/Linux
### Device
PC
### Browser & Version
Google Chrome 84.0.4147.105
### Steps to reproduce
1. Visit https://demos.creative-tim.com/vue-argon-dashboard-pro/#/tables/paginated (or run locally and visit http://localhost:8081/#/tables/paginated)
2. Type character in search above a table.
### What is expected?
Show matched items.
### What is actually happening?
matched items' contents are hidden.
or does not match at all.

---

**Comment by rarestoma** [comment]
Hi @falsetru,

Thank you for working with our products.

I checked now and it is a problem from the update of fuse.js.

Can you please change its version in package.json to "fuse.js": "^3.2.0" and try again?

Thank you,
Rares

**Comment by falsetru** [comment]
`npm uninstall fuse.js --save && npm install fuse.js@^3.2.0 --save` downgraded fuse.js from 6.4.1 to 3.6.1.
It it solved the issue.
Thanks.

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
