### ISSUE TITLE
[Bug] Wrong usage of swal in paginated tables code

### ISSUE THREAD

**Issue by falsetru** [creativetimofficial/ct-vue-argon-dashboard-pro#31]
### Version
1.2.2
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/#/tables/paginated
### Operating System
Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 GNU/Linux
### Device
PC
### Browser & Version
Google Chrome 84.0.4147.105
### Steps to reproduce
Visit https://demos.creative-tim.com/vue-argon-dashboard-pro/#/tables/paginated (or run locally and visit http://localhost:8081/#/tables/paginated)
Click like button (or edit, delete button)
### What is expected?
alert shown
### What is actually happening?
Nothing happen.
can see error in console:
```
TypeError: Cannot call a class as a function
    at e (sweetalert2.all.js:29)
    at t (sweetalert2.all.js:3103)
    at a.handleDelete (PaginatedTables.vue:204)
    at click (PaginatedTables.vue?443c:4)
    at ne (vee-validate.esm.js:31)
    at HTMLButtonElement.n (vee-validate.esm.js:31)
    at HTMLButtonElement.Gi.o._wrapper (vee-validate.esm.js:31)
```

---
### Solution
Replace `swal(...)` calls with `swal.fire(...)`.

**Comment by rarestoma** [comment]
Hi @falsetru,

Thank you for working with our products and for pointing us this issue.

I just added it to the 'to do' list for the next update.

Thank you,
Rares

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
