### ISSUE TITLE
[Bug] can not run npm run serve or npm run build

### ISSUE THREAD

**Issue by poblepj-tene** [creativetimofficial/ct-vue-argon-dashboard-pro#34]
### Version
2.0.0
### Reproduction link
https://www.youtube.com/watch?v=4lCZjj91Ob0
### Operating System
win10
### Device
notebook
### Browser & Version
chrome  88.0.4324.190
### Steps to reproduce
1. npm i
2. npm run serve

### What is expected?
no error message 
### What is actually happening?
 ERROR  Failed to compile with 1 error                                                                       上午9:12:53

This dependency was not found:

* date-fns/format in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Widgets/CalendarWidget.vue?vue&type=script&lang=js

To install it, you can run: npm install --save date-fns/format

---
### Solution
I have no idea
### Additional comments
please test your product

**Comment by rarestoma** [comment]
Hi @poblepj-tene,

Thank you for working with our products and for pointing us this issue.

I tested it now and it works on my side. Can you please tell me what version of node and npm are you using?

Thank you,
Rares

**Comment by poblepj-tene** [comment]
Hi Rares,

In the issue I had provide the youtube link.
In the end of  my video , I had provide my npm and node version. I hope you watch my video  and see the error message.

 

Best regards,

Paul

**Comment by nanu-c** [comment]
The problem here is, that the github repository was removed
```
yarn add date-fns/format
yarn add v1.22.10
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/date-fns/format.git
```

**Comment by nanu-c** [comment]
It's used in `CalendarWidget.vue` but not in the `package.json`

**Comment by poblepj-tene** [comment]
How to solve this problem? 
If that  Github, "date-fns/format", had been removed, why did @rarestoma say he could successfully test it? Please give us the correct steps or upload the correct version.

**Comment by wmsoftware-de** [comment]
I had the same problem, solved it with 
sudo npm install -g npm@latest

**Comment by soulgarden** [comment]
Same problem
**OS:** Macos 11.2.2 (20D80)
**Node version:** v15.11.0
**Yarn version:** 1.22.10
**Npm version:** 7.6.3

```
yarn run build
yarn run v1.22.10
$ vue-cli-service build

⠴  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                        10:28:03 PM

This dependency was not found:

* date-fns/format in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Widgets/CalendarWidget.vue?vue&type=script&lang=js

To install it, you can run: npm install --save date-fns/format
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Try to install dependency with npm:

```
npm install date-fns/format
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/date-fns/format.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

Try to install dependency with yarn:

```
yarn add date-fns/format --save        
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/date-fns/format.git
Directory: /private/var/www/stockswayup-frontend
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by rarestoma** [comment]
Hi @soulgarden,

Thank you for working with our products.

Please try to install date-fns using the following command: `npm install date-fns`.

Please let me know if it works.

Thank you,
Rares

**Comment by poblepj-tene** [comment]
After executing the script, "npm install date-fns" , the problem is solved.
Please update your package.json .

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
