### ISSUE TITLE
[Bug] <html-editor v-model… not working in V2

### ISSUE THREAD

**Issue by wmsoftware-de** [creativetimofficial/ct-vue-argon-dashboard-pro#36]
### Version
2
### Reproduction link
https://www.google.com
### Operating System
macOS
### Device
Desktop
### Browser & Version
Chrome 89.0.4389.82
### Steps to reproduce
html-editor v-model="action.HTML_Text" 

import HtmlEditor from "@/components/Inputs/HtmlEditor";
export default {
name: "ActionEdit",
components: {
HtmlEditor,
…

### What is expected?
Text in the editor and v-model action.HTML_Text is synced
### What is actually happening?
Text in the editor and v-model action.HTML_Text is **not** synced

---
### Additional comments
It worked in V1.x

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

Thank you for working with our products and for pointing us this issue.

Can you please give me the whole code so I can test it and see how can I fix it?

Thank you,
Rares

**Comment by wmsoftware-de** [comment]
Use your example from https://www.creative-tim.com/learning-lab/bootstrap-vue/quill/argon-dashboard

and bind a variable to the editor: 

```
<script>
import HtmlEditor from '@/components/Inputs/HtmlEditor'


export default {
  components: {
    HtmlEditor
  },
 data: function () {
    return {
      HTML_Text: "ABCDEF",
}
}
}

</script>


<form>
  <html-editor v-model="HTML_Text"></html-editor>
</form>
```

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

I tried now and it is true, v-model is no longer working on HtmlEditor. 

I tried by replacing `v-model="HTML_Text"` with `:value="HTML_Text"` and it works.

Please let me know if it works.

Thank you,
Rares

**Comment by wmsoftware-de** [comment]
Does not work here:

`                  <html-editor :value="HTML_Text" />
                    {{HTML_Text}}
`
<img width="314" alt="htmleditor" src="https://user-images.githubusercontent.com/75385458/111488999-0d8b0680-873a-11eb-80ee-a18d9a81c732.png">

**Comment by wmsoftware-de** [comment]
No solution?

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

We didn't find a solution yet. We will still do tests to solve this issue.

Thank you,
Rares

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

Please try the following:

In src/components/Inputs/HtmlEditor.vue, replace, from line 53 the "text-change" function with the following:

 ```
let html = node.innerHTML;
        if (html === "<p><br></p>") {
          html = "";
        }
        this.content = html;
        this.$emit("update:modelValue", this.content);
        this.$emit("input", this.content);
      });
```

After that, use the html-editor the following way:

```
  <html-editor :value="HTML_Text" v-model="HTML_Text"></html-editor>
    {{ HTML_Text }}
```

Please let me know if it works for you.

Thank you,
Rares

**Comment by wmsoftware-de** [comment]
On the first impression it works. Changes are reflected in HTML_Text. Unfortunately using bold/italic/underline buttons on pre-populated text does not work. This happens even with text previously entered in html-editor

Errors:

quill.js?9339:5824 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at TextBlot.ShadowBlot.insertInto (webpack-internal:///./node_modules/quill/dist/quill.js:5819:32)
    at Proxy.ContainerBlot.insertBefore (webpack-internal:///./node_modules/quill/dist/quill.js:3463:19)
    at Proxy.insertBefore (webpack-internal:///./node_modules/quill/dist/quill.js:923:103)
    at TextBlot.split (webpack-internal:///./node_modules/quill/dist/quill.js:7627:21)
    at TextBlot.ShadowBlot.isolate (webpack-internal:///./node_modules/quill/dist/quill.js:5825:27)
    at TextBlot.ShadowBlot.formatAt (webpack-internal:///./node_modules/quill/dist/quill.js:5792:25)
    at eval (webpack-internal:///./node_modules/quill/dist/quill.js:3443:19)
    at LinkedList.forEachAt (webpack-internal:///./node_modules/quill/dist/quill.js:7127:17)
    at Block.ContainerBlot.formatAt (webpack-internal:///./node_modules/quill/dist/quill.js:3442:23)
    at BlockBlot.formatAt (webpack-internal:///./node_modules/quill/dist/quill.js:7468:39)
ShadowBlot.insertInto @ quill.js?9339:5824
ContainerBlot.insertBefore @ quill.js?9339:3468
insertBefore @ quill.js?9339:928
TextBlot.split @ quill.js?9339:7632
ShadowBlot.isolate @ quill.js?9339:5830
ShadowBlot.formatAt @ quill.js?9339:5797
eval @ quill.js?9339:3448
LinkedList.forEachAt @ quill.js?9339:7132
ContainerBlot.formatAt @ quill.js?9339:3447
BlockBlot.formatAt @ quill.js?9339:7473
formatAt @ quill.js?9339:898
eval @ quill.js?9339:3448
LinkedList.forEachAt @ quill.js?9339:7132
ContainerBlot.formatAt @ quill.js?9339:3447
ScrollBlot.formatAt @ quill.js?9339:7214
formatAt @ quill.js?9339:4304
eval @ quill.js?9339:2594
formatText @ quill.js?9339:2593
eval @ quill.js?9339:1261
modify @ quill.js?9339:1660
format @ quill.js?9339:1250
eval @ quill.js?9339:9471
quill.js?9339:7255 Uncaught RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at optimize (quill.js?9339:7255)
    at LinkedList.forEach (quill.js?9339:7121)
    at optimize (quill.js?9339:7256)
    at LinkedList.forEach (quill.js?9339:7121)
    at optimize (quill.js?9339:7256)
    at LinkedList.forEach (quill.js?9339:7121)
    at optimize (quill.js?9339:7256)
    at LinkedList.forEach (quill.js?9339:7121)
    at optimize (quill.js?9339:7256)

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

Thank you for pointing this issue. I will still do some test to find a solution.

Thank you,
Rares

**Comment by wmsoftware-de** [comment]
20 days later: no solution?

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

We didn't find yet a solution for this issue yet.. We also added it to the 'to do' list for the next update.

Thank you,
Rares

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
