### ISSUE TITLE
[Bug] @click in base-button is executed twice in V2

### ISSUE THREAD

**Issue by wmsoftware-de** [creativetimofficial/ct-vue-argon-dashboard-pro#37]
### Version
2
### Reproduction link
https://www.google.com
### Operating System
macOS
### Device
Desktop
### Browser & Version
Chrome 89.0.4389.82
### Steps to reproduce
 <base-button type="primary" @click="test()">Button</base-button>

   test() {
      console.log("Test");
    },
### What is expected?
1 entry in console
### What is actually happening?
2 entries in console

---
### Additional comments
Worked in V1

**Comment by rarestoma** [comment]
Hi @wmsoftware-de,

Thank you for working with our products and for pointing us this issue.

To fix this, go to the BaseButton component (`src/components/BaseButton.vue`) and remove  `@click="handleClick"`.

Please let me know if it works.

Thank you,
Rares

**Comment by wmsoftware-de** [comment]
Thanks, that solves the problem.

**Comment by Biegal** [comment]
Hi,

Why there is no new release with fixes like that?
Great that it was solved here, but version on the creative-tim still has this bug (which led me here ....)

**Comment by rarestoma** [comment]
Hi @Biegal,

Thank you for working with our products.

Can you please tell me what version are you using?

Thank you,
Rares

**Comment by Biegal** [comment]
Hi @rarestoma !
It says 2.0.0 on the portal

**Comment by rarestoma** [comment]
Hi @Biegal,

I tried now the example from above in the v2.0.0 version and it works.

Can you please try the following test?

```
<base-button type="primary" @click="test()">Button</base-button>

test() {
console.log("Test");
}
```

Please let me know if it works.

Thank you,
Rares

**Comment by Biegal** [comment]
So I just went to https://www.creative-tim.com/downloads , downloaded Vue Argon Dashboard Pro which says version 2, added snippet that you've mentioned (I've added it to dashboard if that makes a difference, but I don't think so) and it fires twice - I've got two logs in the console.

My BaseButton starts like this:
```
<template>
  <component
    :is="tag"
    :type="tag === 'button' ? nativeType : ''"
    :disabled="disabled || loading"
    @click="handleClick"
    class="btn base-button"
    :class="[
      { 'rounded-circle': round },
      { 'btn-block': block },
      { 'btn-wd': wide },
      { 'btn-icon btn-fab': icon },
      { [`btn-${type}`]: type && !outline },
      { [`btn-${size}`]: size },
      { [`btn-outline-${type}`]: outline && type },
      { 'btn-link': link },
      { disabled: disabled && tag !== 'button' },
    ]"
  >
```
so it doesn't have fix mentioned above.


I'm trying to figure out if there is a newer version of codebase than I have, before I will post other issue for example (it seems baseInput doesn't work with v-model? )

**Comment by TucciAlessandro** [comment]
Hi Biegal, have you found a solution to  ` I'm trying to figure out if there is a newer version of codebase than I have, before I will post other issue for example (it seems baseInput doesn't work with v-model? ) `? I am having the same issue

**Comment by Biegal** [comment]
Hi @TucciAlessandro, as you see here I didn't get any more info from @rarestoma (or anyone else).
I have no idea where is the latest and gratest version, which is sad.
Currently I'm using a codebase from the https://www.creative-tim.com/downloads and I've made some fixes myself so it works in my scenarios :/
Not great, but .....

**Comment by TucciAlessandro** [comment]
Yeah.. Would you mind sharing those fixes with me ?

**Comment by rarestoma** [comment]
Hi @Biegal @TucciAlessandro,

Thank you for working with our products and sorry for my late response.

I just tested now and you are right, it still happens. I was testing it in `v2.0.1` but we didn't launch yet this version as we still have a few changes to make.

Please go to the `BaseButton` component (`src/components/BaseButton.vu`e) and remove `@click="handleClick"`. I just added it for the next version update

Please let me know if it works.

Thank you,
Rares

**Comment by TucciAlessandro** [comment]
Hi rarestoma, that works for the double event being fired, thank you..  but the most concerning is the v-model  on base-inputs that it doesn't seem to work (maybe becaused used with the usefield() from vee-validate). Also  i am having trouble with the mobile toggleMenu button that is not working as intended( not opening menu ).. 
Thank you!

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
