### ISSUE TITLE
Sidebar issue when width is below 1200px

### ISSUE THREAD

**Issue by crazynoob01** [creativetimofficial/ct-vue-argon-dashboard-pro#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [v ] I am running the latest version
- [ v] I checked the documentation and found no answer
- [v ] I checked to make sure that this issue has not already been filed
- [ v] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
The sidebar should be hidden when the demo website width below 1200px

# Current Behavior
The sidebar is not hidden when the demo website width below 1200px

# Failure Information (for bugs)

## Steps to Reproduce

1.  Readjust the width to below 1200px

**Comment by cristijora** [comment]
This issue has been fixed in v1.2.0 along with some other issues & improvements. For more details check out this [changelog](https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/changelog.html#_1-2-0-2020-01-05)
