### ISSUE TITLE
[Bug] bug with the search button on smartphone

### ISSUE THREAD

**Issue by madinina95** [creativetimofficial/ct-vue-argon-dashboard-pro#40]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.183977317.2108132897.1621681239-1643538524.1612306752#/dashboard
### Operating System
Linux
### Device
Google Pixel 4
### Browser & Version
chrome latest
### Steps to reproduce
1. Go to the dashboard route : https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.104311235.2108132897.1621681239-1643538524.1612306752#/dashboard
2. open the mobile simulator on Chrome or open it on any smartphone
3. Click on the search icon
### What is expected?
a search field should appear
### What is actually happening?
Nothing happens

---

**Comment by rarestoma** [comment]
Hi @madinina95,

Thank you for working with our products.

I will add this feature to the discussion for the next updates.

Best regards,
Rares

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
