### ISSUE TITLE
[Bug] The input value of base-input is cleared.

### ISSUE THREAD

**Issue by mineoni** [creativetimofficial/ct-vue-argon-dashboard-pro#41]
### Version
2.0.0
### Reproduction link
https://codepen.io/bussinesOnizuka/pen/GRWEzEM
### Operating System
Windows10
### Device
PC
### Browser & Version
Chrome 90.0.4430.212
### Steps to reproduce
1. Here is the code 
＜base-input name="testinput" /＞

2. The following script
testinput.value = "aaaa"

3.The value is set in the form on the screen and can get it from script.
However, when I focus on it, the value is cleared. 

### What is expected?
The value should continue to be held in the input form.
### What is actually happening?
The value disappears when focusing.

---

**Comment by TucciAlessandro** [comment]
It seems i have a sort of the same problem with base-input, v-model doesn't work on it. why?

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
