### ISSUE TITLE
[Bug] dropzone-file-upload is not working

### ISSUE THREAD

**Issue by mineoni** [creativetimofficial/ct-vue-argon-dashboard-pro#42]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.45882083.655152236.1618795484-1969098138.1616570306#/forms/components
### Operating System
Windows10
### Device
PC
### Browser & Version
Chrome 90.0.4430.212
### Steps to reproduce
1. Import dropzone-file-upload and add it to components.
2. Add dropzone-file-upload tag on vue file.
3. Bind an array to v-model.
4. drop file to dropzone area.
5. When I print the contents of the bound array to the console, there are no elements.
### What is expected?
I should have been able to see the elements of the array.
### What is actually happening?
nothing

---
### Solution
nothing
### Additional comments
why?

**Comment by rarestoma** [comment]
Hi @mineoni,

Thank you for working with our products and sorry for my late response.

Can you please give me the code that you tried so I can test it and see what happens/find a solution?

Best regards,
Rares

**Comment by mineoni** [comment]
https://demos.creative-tim.com/vue-argon-dashboard-pro/documentation/plugins/dropzone.html

I think the sample code in this document is insufficient.

In most cases, the process after file selection is written.
In many cases, I write the process after file selection, but this sample doesn't describe that much.
(v-model binding only)

I would like you to provide the code to get the set file.

**Comment by henning150** [comment]
The file is not available on event "addedfile", maybe the filereader takes too long, but "thumbnail" event works

My temperary fix is to add @ thumbnail listener to the dropzone-file-upload element where the data is available

`<dropzone-file-upload v-model="temp" @thumbnail="change"></dropzone-file-upload>`

and 

`change(file) {
       this.file = file.dataURL;
}`

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
