### ISSUE TITLE
[Bug] HTML Editor

### ISSUE THREAD

**Issue by Cantador1992** [creativetimofficial/ct-vue-argon-dashboard-pro#44]
### Version
Version 2.0.0
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.83721682.553097670.1632405563-2137332924.1631090826#/forms/components
### Operating System
Windows 10
### Device
PC
### Browser & Version
Mozilla
### Steps to reproduce
Nothing, same happens in your live demo
### What is expected?
Write spaces between words in HTML editor
### What is actually happening?
Not writing spaces between words in HTML editor

---

**Comment by Cantador1992** [comment]
Forgot to mention, its only happening in FIREFOX

**Comment by rarestoma** [comment]
Hi @Cantador1992,

Thank you for working with our products.

Can you please tell me what version of Firefox are you using? I tried now on 92.0 on macOS and it works fine.

Thank you,
Rares

**Comment by Cantador1992** [comment]
Hello, I am using 93.0b9 (64-bit) firefox developper edition

**Comment by Cantador1992** [comment]
Té lhogueee

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
