### ISSUE TITLE
[Bug] unable to resolve dependency tree    

### ISSUE THREAD

**Issue by Spring302** [creativetimofficial/ct-vue-argon-dashboard-pro#46]
### Version
vue-argon-dashboard-pro-v2.0.0
### Reproduction link
https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro
### Operating System
windows 10
### Device
pc
### Browser & Version
@vue/cli 4.5.15, npm@8.5.3
### Steps to reproduce
1. Download File in link [https://www.creative-tim.com/club-member]
2. access this Folder
3. "npm i"
4. get error
"
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-argon-dashboard-pro@2.0.0
npm ERR! Found: eslint@7.21.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.21.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.11
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
"

### What is expected?
I don't know front-end, so help plz.
I want just npm module installing.
### What is actually happening?
dependency error

---
### Solution
in macos, it work (npm i).

**Comment by rarestoma** [comment]
Hi @Jarry-Ha,

Thank you for working with our products.

Can you please tell me what version of node are you using?

Thank you,
Rares

**Comment by Spring302** [comment]
Hello @rarestoma !

I use node v12.22.10.

Thank you.

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
