### ISSUE TITLE
[Bug] Cannot install by using npm OR yarn

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-vue-argon-dashboard-pro#47]
### Version
2.0.0
### Reproduction link
https://github.com/bartam-39/vue-app
### Operating System
MacOS 12.2.1
### Device
MacBook Pro 16'
### Browser & Version
 nd
### Steps to reproduce
Download the file from you website.
Unzip it.
install the dependency --> get the error.

look at the additional comments for the error.

node version: v16.14.0
yarn version: 1.22.27
npm version: 8.3.1
### What is expected?
build.
### What is actually happening?
dependency error.

---
### Additional comments
error /Users/user/Develop/git/vue-app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/user/Develop/git/vue-app/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/user/Develop/git/vue-app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/user/Develop/git/vue-app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@7.1.2
gyp info using node@16.14.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp verb find Python - executing "/Library/Developer/CommandLineTools/usr/bin/python3" to get version
gyp verb find Python - version is "3.8.9"
gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 16.14.0
gyp verb command install [ '16.14.0' ]
gyp verb install input version string "16.14.0"
gyp verb install installing version: 16.14.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.14.0
gyp verb build dir attempting to create "build" dir: /Users/user/Develop/git/vue-app/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/user/Develop/git/vue-app/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/user/Develop/git/vue-app/node_modules/node-sass/build/config.gypi
(node:4976) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp verb config.gypi checking for gypi file: /Users/user/Develop/git/vue-app/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/user/Develop/git/vue-app/node_modules/node-sass/common.gypi
gyp verb gyp gyp forma

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
