### ISSUE TITLE
 no horizontal lines in line chart

### ISSUE THREAD

**Issue by Kvasha123** [creativetimofficial/ct-vue-argon-dashboard-pro#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

horizontal white-dots-line in line-chart.

# Current Behavior

The chart is working, except for the white-dots-line.

# Failure Information (for bugs)

I get no error, nor a warning

## Steps to Reproduce

1. installed chart.js and vue-chartjs through npm
    --> npm install chart.js --save
    --> npm install vue-chartjs chart.js --save
2. added the code from the demo example for the dark-blue line-chart
3. imported the LineChart-Component

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:     Desktop-PC
* Operating System:  Win10
* Browser and Version:  All Browsers

## Failure Logs

Please include any relevant log snippets or files here.

-----------------------------------------------------------------------------------
hello there,

i have tried to create a line chart like in the demos and it works except for the white-dot-horizontal lines (in the dark-blue chart).
I thought that the options for this would be in the /components/Charts/config.js.

My Code is the exact code like in the demo-example.

Or is there a npm package that i am missing?

I did install:
npm install chart.js --save
npm install vue-chartjs chart.js --save

Thx in Advance

**Comment by cristijora** [comment]
Hey @Kvasha123 Did you use the initial template and archive as a base project or you set up your own project ?
If it's a custom setup I would recommend copying over the whole "Charts" folder. From dependencies point of vie indeed `chart.js` and `vue-chartjs` should be enough

**Comment by cristijora** [comment]
Will close this due to inactivity
