### ISSUE TITLE
[Bug] Errors in NPM -i

### ISSUE THREAD

**Issue by baldybuilds** [creativetimofficial/ct-vue-argon-dashboard-pro#51]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/
### Operating System
Windows 11
### Device
Computer
### Browser & Version
All
### Steps to reproduce
Running Vue 3 + Node 16.17.1
1. Download latest version of files from website
2. CD into the directory
3. npm -i to install (fails and gets errors)
4. npm -i npm i --legacy-peer-deps (runs and informs me of issues)
5. npm audit fix ( fails with more issues )

$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @vue/cli-plugin-eslint@4.5.11
npm ERR! Found: eslint@7.21.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.21.0" from the root project
npm ERR!   peer eslint@">= 5.0.0" from @vue/eslint-config-prettier@6.0.0
npm ERR!   node_modules/@vue/eslint-config-prettier
npm ERR!     dev @vue/eslint-config-prettier@"6.0.0" from the root project
npm ERR!   5 more (babel-eslint, eslint-config-prettier, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.11
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.11" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.11
npm ERR!   node_modules/@vue/cli-plugin-eslint
npm ERR!     dev @vue/cli-plugin-eslint@"4.5.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

npm ERR! A complete log of this run can be found in:

~/Desktop/New MDT/vue-argon-dashboard-pro-v2.0.0/vue-argon-dashboard-pro-v2.0.0
$ npm i --legacy-peer-deps

up to date, audited 1638 packages in 7s

117 packages are looking for funding
  run `npm fund` for details

37 vulnerabilities (3 moderate, 31 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

~/Desktop/New MDT/vue-argon-dashboard-pro-v2.0.0/vue-argon-dashboard-pro-v2.0.0
$ npm audit fix
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-argon-dashboard-pro@2.0.1
npm ERR! Found: vue@3.0.5
npm ERR! node_modules/vue
npm ERR!   vue@"3.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.2.37" from @vueup/vue-quill@1.0.0-beta.10
npm ERR! node_modules/@vueup/vue-quill
npm ERR!   @vueup/vue-quill@"^1.0.0-beta.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

npm ERR! A complete log of this run can be found in:

### What is expected?
Expected to install the needed files.
### What is actually happening?
Countless errors that I'm unable to resolve.

---

**Comment by Geekhole** [comment]
+1

**Comment by maisamaf** [comment]
Please only run the `npm i --legacy-peer-deps` command and ignore the warnings and skip running the command `npm audit fix` and everything should work fine. Please let me know if the project runs for you?

**Comment by maisamaf** [comment]
Hi @enlistedmango and @Geekhole 
Please only run the `npm i --legacy-peer-deps` command and ignore the warnings and everything should work fine. 

Regards,
Maisam
