### ISSUE TITLE
[Feature Request] Single Nav Item with icon

### ISSUE THREAD

**Issue by ataldev** [creativetimofficial/ct-vue-argon-dashboard-pro#53]
### What is your enhancement?
The whole purpose of purchasing a template is that it comes with ready-to-use code. There are a lot of things missing and things that do not work and need manual work.
For starters, I need a single nav link (not an item within collapse) that serves as a router-link. There is one on the template, i.e. changelog, but that only serves as a normal link and not a router-link.

**Comment by ataldev** [comment]
To add, there are so many problems with accessibility. In order to make the template accessible, one has to spend twice the development time. I recommend you run WAVE before you publish the template.

**Comment by sajadevo** [comment]
Hey @depressedpsychiatrist,

Could you please tell me which parts are missing and what needs to be done manually, our products are used as a starter template not a complete ready to production project, please use it to build the base of their projects and then do their own works like putting new pages and layouts based on their needs.
A starter template or theme is for getting your works done faster not to bring all the features for any type of projects.

If you need everything based on your needs then just contact us using our [Custom Development Services](https://services.creative-tim.com/).

Regards,
Sajad
