### ISSUE TITLE
[Bug] Dropdown menu are inconsistent, sometimes you click it flicks and auto closes, plus popper warning in the console

### ISSUE THREAD

**Issue by abusham1993** [creativetimofficial/ct-vue-argon-dashboard-pro#55]
### Version
3.0.1
### Reproduction link
https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.168617638.668562822.1682191141-1618090742.1682191141#/dashboards/dashboard-default
### Operating System
Mac OS
### Device
Macbook pro
### Browser & Version
Chrome 112.0.5615.137
### Steps to reproduce
You can easily reproduce the issues in the demo link I have provided.

In the demo, default dashboard page, in the navbar, press the notification icon
- it shows warnings in the console.
- try opening the dropdown, then click anywhere to close it, then try to open the dropdown again, it flicks and doesn't work.
### What is expected?
- no styles warning for popper in console
- dropdown to work without the flickering
### What is actually happening?
- warnings regarding poppers styling
- notification dropdown flickers and not working well

---

**Comment by sajadevo** [comment]
Hey there,

Thanks for using our product, could you please share a short video related to this issue?

Regards,
Sajad

**Comment by abusham1993** [comment]
https://user-images.githubusercontent.com/122645156/235216449-29e3a16b-5e09-4018-b285-f4d806853184.mp4

 in the demo https://demos.creative-tim.com/vue-argon-dashboard-pro/?_ga=2.168617638.668562822.1682191141-1618090742.1682191141#/dashboards/dashboard-default
 
 try to open dropdown menu (notifications) then close it by clicking outside, and try to open it again. it doesn't open! and locally, it tries to open but flicks and re-closes. plus in the console it show the following error:
 
 poppper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.

**Comment by sajadevo** [comment]
Hey there,

Thanks for reporting this we'll try to fix it ASAP.

Regards,
Sajad

**Comment by abusham1993** [comment]
Thank you Sajad, looking forward.

**Comment by abusham1993** [comment]
hello @sajadevo, following up on this.

**Comment by abusham1993** [comment]
Hello @sajadevo.

Its been more than a month! can you please advise.

**Comment by abusham1993** [comment]
@sajadevo We have purchased the company license and I am expecting a better after sales support!

**Comment by sajadevo** [comment]
Hey there, 

We're updating our products 3 to 4 products per day and our developer is working on issues like this once we released the Argon we'll inform you.

Regards,
Sajad

**Comment by maisamaf** [comment]
Hey @abusham1993,

Sorry for the inconvenience. To fix the issue, please add `@blur="closeMenu"` listener to the anchor element with the id of `dropdownMenuButton` in the `Navbar.vue` component. Then define the following method:

```
methods: {
    // remaining code
   closeMenu() {
      setTimeout(() => {
        this.showMenu = false;
      }, 100);
    },
}
```
This issue will be fixed in our upcoming update. Thank you for using our products.

Best regards,
Maisam Afshar

**Comment by abusham1993** [comment]
Hello @maisamaf,

That solved the problem, thank you for following up.
Closing the card for now.

Best regards,
Abdullah.
